<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PadelManager.Models\PadelManager.Models.csproj" />
    <ProjectReference Include="..\PadelManager.Repositories\PadelManager.Repositories.csproj" />
  </ItemGroup>

</Project>
